### ISSUE TITLE
[Mod Interaction] Modern Skyblock 2 crash pulling smart combustion controller

### ISSUE THREAD

**Issue by BrianEdmonds** [Bartz24/SkyResources#120]
I'm playing Modern Skyblock 2 on a private server, and just this morning progressed far enough to deploy a smart combustion controller. Silly me I misread the instructions and put it on the top, under the sticky piston I use to open and close the chamber. I went to take it apart, and hit the switch to retract the piston to pull the top up so I could hop in to grab it if fell in. The server immediately crashed. The server restarted fine, and after logging in the controller block had vanished.

Looks like a null pointer exception in Sky Resources:

```
[05:37:04] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
        at com.bartz24.skyresources.technology.block.BlockCombustionController.func_180663_b(BlockCombustionController.java:165) ~[BlockCombustionController.class:?]
        at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:567) ~[axw.class:?]
        at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?]
        at net.minecraft.block.BlockPistonBase.func_176319_a(BlockPistonBase.java:368) ~[awj.class:?]
        at net.minecraft.block.BlockPistonBase.func_189539_a(BlockPistonBase.java:246) ~[awj.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]   
        at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1224) ~[oo.class:?]
        at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1211) ~[oo.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by Bartz24** [comment]
a similar crash just happened in msb3, but not with Sky Resources only.
sounds like a mod interaction issue

**Comment by FusionLord** [comment]
Looks to my like the tile was destroyed prior to the block. As for how that happened I'm not sure.
