### ISSUE TITLE
1.0.0 producing console spam but still works nonetheless

### ISSUE THREAD

**Issue by kreezxil** [Bartz24/SkyResources#17]
When a player issues /platform visit <playername> the command still works but the dedicated server reports the following in console

The server is on Forge 2065

```
[15:51:03] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.MinecraftServer.func_184104_a(MinecraftServer.java:862) ~[MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147341_a(NetHandlerPlayServer.java:1286) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:52) ~[il.class:?]
        at net.minecraft.network.play.client.CPacketTabComplete.func_148833_a(SourceFile:11) ~[il.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by Bartz24** [comment]
So, this was all there was when running the cmd?

**Comment by Bartz24** [comment]
There isn't anything in the dev server, but I would recommend trying it with only Sky Resources as I don't have an actual server.
