### ISSUE TITLE
Latest build don't start

### ISSUE THREAD

**Issue by TheGuyFromTheInternet** [Bartz24/SkyResources#4]
skyresources-0.6.6 Alpha.jar crashes the game from the get go. Even I tried loading it on its own.

Here is the crash report:

> 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  LoadingPlugin (Quark-beta-28.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 6/23/16 8:54 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:589)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at com.bartz24.skyresources.config.ConfigOptions.loadConfigThenSave(ConfigOptions.java:157)
	at com.bartz24.skyresources.proxy.CommonProxy.preInit(CommonProxy.java:37)
	at com.bartz24.skyresources.proxy.ClientProxy.preInit(ClientProxy.java:15)
	at com.bartz24.skyresources.SkyResources.preInit(SkyResources.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
	... 10 more
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 250494224 bytes (238 MB) / 524288000 bytes (500 MB) up to 716177408 bytes (683 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx768m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1967 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1967.jar) 
	UCH	Forge{12.17.0.1967} [Minecraft Forge] (forge-1.9.4-12.17.0.1967.jar) 
	UCH	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UCH	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcake-1.9.4-0.0.1.jar) 
	UCH	endercore{1.9.4-0.4.0.26-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.26-alpha.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.9.4-3.0.0.45_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.45_alpha.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UCH	inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks] (InventoryTweaks-1.61-beta-54.jar) 
	UCH	IronChest{6.0.145.787} [Iron Chest] (ironchest-1.9.4-6.0.145.787.jar) 
	UCH	jacb{1.0.6} [JACB] (JACB-1.9.4-1.0.6.jar) 
	UCH	JEI{3.6.7.216} [Just Enough Items] (jei_1.9.4-3.6.7.216.jar) 
	UCH	jeresources{0.4.6.35} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.6.35.jar) 
	UCH	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4b.jar) 
	UCH	Quark{beta-28} [Quark] (Quark-beta-28.jar) 
	UCE	skyresources{0.6.6 Alpha} [Sky Resources] (skyresources-0.6.6 Alpha.jar) 
	UCH	terrainCrystals{1.0.8} [Terrain Crystals] (Terrain Crystals - 1.9.4 - 1.0.8.jar) 
	UCH	wailafeatures{0.3.1.11} [WAILA Features] (WAILA-features-1.9.4-0.3.1.11.jar) 
	UCH	Woot{1.9.4-0.3.0-beta} [Woot] (woot-1.9.4-0.3.0-beta.jar) 
	Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-beta-28.jar)
  vazkii.quark.base.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'Intel' Version: '3.0.0 - Build 8.15.10.2279' Renderer: 'Intel(R) HD Graphics Family'
	EnderIO: No known problems detected.
<

**Comment by Bartz24** [comment]
Fixed
