### ISSUE TITLE
[1.12.1] post-init recipe crash

### ISSUE THREAD

**Issue by Yoghurt4C** [Bartz24/SkyResources#73]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Sky Resources 2 (skyresources)
Caused by: java.lang.RuntimeException: Invalid shaped ore recipe: XXX, XYX, XXX, X, ingotIron, Y, null, 
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:344)
	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:68)
	at com.bartz24.skyresources.registry.CraftingRegistry.addShapedOreRecipe(CraftingRegistry.java:61)
	at com.bartz24.skyresources.registry.ModCrafting.init(ModCrafting.java:600)
	at com.bartz24.skyresources.proxy.CommonProxy.init(CommonProxy.java:54)
	at com.bartz24.skyresources.proxy.ClientProxy.init(ClientProxy.java:34)
	at com.bartz24.skyresources.SkyResources.init(SkyResources.java:40)

version 2.0.19
forge 2446

**Comment by Bartz24** [comment]
hotfix coming soon

**Comment by Bartz24** [comment]
hotfix coming soon
