### ISSUE TITLE
crash on using the Tomb with books

### ISSUE THREAD

**Issue by Titanblade828** [Bartz24/SkyResources#92]
First time reporting anything so i think this is what you need ?
all i did was open the book and select a book to read and it crashed on me

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (applied-llamagistics-1.12.1-rv5-beta-9.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.4.8.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.6.1.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.1-1.12-anarchy.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Quark-r1.3-111.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.3.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.13.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 10/14/17 7:25 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.buuz135.industrial.api.book.page.PageRecipe.drawScreenPre(PageRecipe.java:32)
	at com.buuz135.industrial.api.book.gui.GUIBookPage.drawScreenBack(GUIBookPage.java:26)
	at com.buuz135.industrial.api.book.gui.GUIBookBase.func_73863_a(GUIBookBase.java:92)
	at com.buuz135.industrial.api.book.gui.GUIBookPage.func_73863_a(GUIBookPage.java:37)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.buuz135.industrial.api.book.page.PageRecipe.drawScreenPre(PageRecipe.java:32)
	at com.buuz135.industrial.api.book.gui.GUIBookPage.drawScreenBack(GUIBookPage.java:26)
	at com.buuz135.industrial.api.book.gui.GUIBookBase.func_73863_a(GUIBookBase.java:92)
	at com.buuz135.industrial.api.book.gui.GUIBookPage.func_73863_a(GUIBookPage.java:37)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

-- Screen render details --
Details:
	Screen name: com.buuz135.industrial.api.book.gui.GUIBookPage
	Mouse location: Scaled: (467, 330). Absolute: (935, 327)
	Screen size: Scaled: (840, 494). Absolute: (1680, 987). Scale factor of 2

**Comment by Bartz24** [comment]
This is not a Sky Resources issue, nothing about this mod is even mentioned.

This looks like an issue for Industrial Foregoing :D
